app = "litellm-proxy-yuki"
primary_region = "nrt"  # Tokyo region, change as needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  API_KEYS_FILE = "/app/data/api_keys.json"
  ENABLE_CACHING = "true"
  CACHE_TTL = "3600"
  MAX_TOKENS_PER_REQUEST = "4000"
  # Set these secrets using fly secrets set
  # OPENAI_API_KEY = ""
  # ANTHROPIC_API_KEY = ""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  # CORS settings
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[services.ports]]
  port = 8080
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[mounts]
  source = "litellm_data"
  destination = "/app/data"

# Resource allocation
[services.concurrency]
  hard_limit = 100
  soft_limit = 80

# Memory allocation
[[vm]]
  memory = "512MB"
  cpu_kind = "shared"
  cpus = 1